import IprStatusDoc from '../type/ipr-status-name';

export interface EmployeeGoalPlan {
  id: number;
  name: string;
  position: string;
  goal: string;
  date: string;
  progress: number;
  taskAll: number;
  taskDone: number;
  status: IprStatusDoc;
}

export const testData = [
  {
    id: 1,
    name: 'Хорошёва Анна Викторовна',
    position: 'Руководитель дирекции',
    goal: 'Карьерный рост',
    date: '10.01.2024',
    progress: 25,
    taskAll: 10,
    taskDone: 4,
    status: IprStatusDoc.NotCompleted,
  },
  {
    id: 2,
    name: 'Иванов Пётр Александрович',
    position: 'Руководитель дирекции',
    goal: 'Повышение грейда',
    date: '01.04.2024',
    progress: 50,
    taskAll: 2,
    taskDone: 1,
    status: IprStatusDoc.InProgress,
  },
  {
    id: 3,
    name: 'Кириллов Константин Соломонович',
    position: 'Руководитель дирекции',
    goal: 'Соответствие занимаемой должности',
    date: '01.07.2024',
    progress: 80,
    taskAll: 5,
    taskDone: 4,
    status: IprStatusDoc.InProgress,
  },
  {
    id: 4,
    name: 'Евсеев Антон Иванович',
    position: 'Руководитель дирекции',
    goal: 'Развитие софт-скиллов',
    date: '01.03.2024',
    progress: 100,
    taskAll: 3,
    taskDone: 3,
    status: IprStatusDoc.Completed,
  },
  {
    id: 5,
    name: 'Чаевская Евгения Владимировна',
    position: 'Руководитель дирекции',
    goal: 'Развитие хард-скиллов',
    date: '05.02.2024',
    progress: 100,
    taskAll: 5,
    taskDone: 5,
    status: IprStatusDoc.Completed,
  },
  {
    id: 6,
    name: 'Хорошёва Анна Викторовна',
    position: 'Руководитель дирекции',
    goal: 'Карьерный рост',
    date: '01.12.2023',
    progress: 0,
    taskAll: 3,
    taskDone: 0,
    status: IprStatusDoc.Canceled,
  },
  {
    id: 7,
    name: 'Константинопольский Константин Константинович',
    position: 'Руководитель дирекции',
    goal: 'Смена специализации',
    date: '01.08.2024',
    progress: 0,
    taskAll: 4,
    taskDone: 0,
    status: IprStatusDoc.Draft,
  },
  {
    id: 8,
    name: 'Алексеев Сергей Степанович',
    position: 'Руководитель дирекции',
    goal: 'Получение нового опыта',
    date: '',
    progress: 0,
    taskAll: 6,
    taskDone: 0,
    status: IprStatusDoc.Draft,
  },
  {
    id: 9,
    name: 'Сошнева Инна Павловна',
    position: 'Руководитель дирекции',
    goal: '',
    date: '',
    progress: 0,
    taskAll: 0,
    taskDone: 0,
    status: IprStatusDoc.NoIpr,
  },
  {
    id: 10,
    name: 'Васильев Олег Александрович',
    position: 'Руководитель дирекции',
    goal: '',
    date: '',
    progress: 0,
    taskAll: 0,
    taskDone: 0,
    status: IprStatusDoc.NoIpr,
  },
  {
    id: 11,
    name: 'Хорошёва Анна Викторовна',
    position: 'Руководитель дирекции',
    goal: 'Карьерный рост',
    date: '10.01.2024',
    progress: 25,
    taskAll: 4,
    taskDone: 1,
    status: IprStatusDoc.NotCompleted,
  },
  {
    id: 12,
    name: 'Иванов Пётр Александрович',
    position: 'Руководитель дирекции',
    goal: 'Повышение грейда',
    date: '01.04.2024',
    progress: 50,
    taskAll: 4,
    taskDone: 2,
    status: IprStatusDoc.InProgress,
  },
  {
    id: 13,
    name: 'Кириллов Константин Соломонович',
    position: 'Руководитель дирекции',
    goal: 'Соответствие занимаемой должности',
    date: '01.07.2024',
    progress: 70,
    taskAll: 10,
    taskDone: 7,
    status: IprStatusDoc.InProgress,
  },
  {
    id: 14,
    name: 'Евсеев Антон Иванович',
    position: 'Руководитель дирекции',
    goal: 'Развитие софт-скиллов',
    date: '01.03.2024',
    progress: 100,
    taskAll: 7,
    taskDone: 7,
    status: IprStatusDoc.Canceled,
  },
  {
    id: 15,
    name: 'Чаевская Евгения Владимировна',
    position: 'Руководитель дирекции',
    goal: 'Развитие хард-скиллов',
    date: '05.02.2024',
    progress: 100,
    taskAll: 8,
    taskDone: 8,
    status: IprStatusDoc.Canceled,
  },
  {
    id: 16,
    name: 'Хорошёва Анна Викторовна',
    position: 'Руководитель дирекции',
    goal: 'Карьерный рост',
    date: '01.12.2023',
    progress: 0,
    taskAll: 5,
    taskDone: 0,
    status: IprStatusDoc.Canceled,
  },
  {
    id: 17,
    name: 'Константинопольский Константин Константинович',
    position: 'Руководитель дирекции',
    goal: 'Смена специализации',
    date: '01.08.2024',
    progress: 0,
    taskAll: 4,
    taskDone: 0,
    status: IprStatusDoc.Draft,
  },
  {
    id: 18,
    name: 'Алексеев Сергей Степанович',
    position: 'Руководитель дирекции',
    goal: 'Получение нового опыта',
    date: '',
    progress: 0,
    taskAll: 2,
    taskDone: 0,
    status: IprStatusDoc.Draft,
  },
  {
    id: 19,
    name: 'Сошнева Инна Павловна',
    position: 'Руководитель дирекции',
    goal: '',
    date: '',
    progress: 0,
    taskAll: 0,
    taskDone: 0,
    status: IprStatusDoc.NoIpr,
  },
  {
    id: 20,
    name: 'Васильев Олег Александрович',
    position: 'Руководитель дирекции',
    goal: '',
    date: '',
    progress: 0,
    taskAll: 0,
    taskDone: 0,
    status: IprStatusDoc.NoIpr,
  },
  {
    id: 21,
    name: 'Васильев Олег Александрович',
    position: 'Руководитель дирекции',
    goal: '',
    date: '',
    progress: 0,
    taskAll: 0,
    taskDone: 0,
    status: IprStatusDoc.NoIpr,
  },
];

export const mentorData = [
  {
    id: 1,
    name: 'Кириллов Константин Соломонович',
    position: 'Руководитель дирекции',
    goal: 'Соответствие занимаемой должности',
    date: '01.07.2024',
    progress: 70,
    taskAll: 10,
    taskDone: 7,
    status: IprStatusDoc.InProgress,
  },
  {
    id: 2,
    name: 'Иванов Пётр Александрович',
    position: 'Руководитель дирекции',
    goal: 'Повышение грейда',
    date: '01.04.2024',
    progress: 50,
    taskAll: 4,
    taskDone: 2,
    status: IprStatusDoc.InProgress,
  },
];
